/* import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// material ui next integration
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Providers from "./lib/provider/Provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children ,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AppRouterCacheProvider>  {children}</AppRouterCacheProvider>
        </body>
      </html>
  );
}
 */

import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "./lib/provider/Providers";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
        <AppRouterCacheProvider>
          <Providers>
              <Toaster position="top-center" richColors />
            <>{children}</>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
